name: push_permission_flow
description: A predictable, testable notification permission flow for Dart and Flutter applications.
version: 0.1.0

repository: https://github.com/hachem-djefafla/push_permission_flow
issue_tracker: https://github.com/hachem-djefafla/push_permission_flow/issues

environment:
  sdk: ^3.8.0

dependencies: {}

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6